[tool.black]
line-length = 88
target-version = ["py39", "py310", "py311"]
[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["backend"]  # Replace "myapp" with your Django app name
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"